// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASMd4WnxDiwjxh7pOCvFzLLIZF5otGaoU',
    appId: '1:812657738177:web:74b643afa1344b66e36f40',
    messagingSenderId: '812657738177',
    projectId: 'team-22-b0928',
    authDomain: 'team-22-b0928.firebaseapp.com',
    storageBucket: 'team-22-b0928.appspot.com',
    measurementId: 'G-P1DS6W98XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5OQphSWptqehuv2xirik92K7ac273f4o',
    appId: '1:812657738177:android:8c9cb4e50e84bbfae36f40',
    messagingSenderId: '812657738177',
    projectId: 'team-22-b0928',
    storageBucket: 'team-22-b0928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQ7cpVLQO7xlUJWPTvoT0IhB5mJRTHtw',
    appId: '1:812657738177:ios:02737b104ac42020e36f40',
    messagingSenderId: '812657738177',
    projectId: 'team-22-b0928',
    storageBucket: 'team-22-b0928.appspot.com',
    iosClientId: '812657738177-dprgvr2c8247kd685k3ac6remdn7p6d3.apps.googleusercontent.com',
    iosBundleId: 'com.example.volunteeringOpportunities',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzQ7cpVLQO7xlUJWPTvoT0IhB5mJRTHtw',
    appId: '1:812657738177:ios:5277b4111544b4b7e36f40',
    messagingSenderId: '812657738177',
    projectId: 'team-22-b0928',
    storageBucket: 'team-22-b0928.appspot.com',
    iosClientId: '812657738177-61h58ruv42kbr2e34aesh3evm5nknpn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.volunteeringOpportunities.RunnerTests',
  );
}
